version: '3.8'
services:
  web:
    build:
      context: ./Python-Flask/
      dockerfile: Dockerfile
    depends_on:
      - redis
    # ports:
    #  - 5000:5000
  redis:
    build:
      context: ./Redis/
      dockerfile: Dockerfile

  myproxy:
    build:
      context: ./Nginx-As-Proxy/
      dockerfile: Dockerfile
    ports:
      - 80:80
  
  nginx-static:
    build:
      context: ./Nginx-Static-Pages/
      dockerfile: Dockerfile